version: 0.2
os     : linux

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
	  - mkdir /usr/share/groovy
	  - mv groovy-2.1.6 /usr/share/groovy/
	  - ln -s /usr/share/groovy/groovy-2.1.6 current
	  - export GROOVY_HOME=/usr/share/groovy/current
	  - export PATH=$GROOVY_HOME/bin:$PATH
	  - export JAVA_HOME=$(/usr/libexec/java_home)
	  
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn cobertura:cobertura package
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - groovy htmlrepot.groovy
artifacts:
  files: 
    - target/EmployeeApplication.war
  discard-paths: yes
