version: 0.2
os     : linux

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes